### PR TITLE
Updated Wallgrove Grid Battery status to operating, added cost and link

### PR DESCRIPTION
**Pull request by mlisowsk**
...as well as start of operations date.
Sources: https://arena.gov.au/projects/transgrid-wallgrove-battery/
and project report https://arena.gov.au/knowledge-bank/transgrid-wallgrove-battery-lessons-learnt-2/ which states on page 3 that "the project commenced Commercial operations in December 2021".

### CODE REVIEW

**Comment by lorenz-g** [comment]
Thanks for that!

**Comment by mlisowsk** [comment]
Glad to help! By the way I think the three projects mention on this page are missing in your list, no?
https://www.energy-storage.news/tesla-megapacks-picked-for-edifys-300mwh-australia-battery-portfolio/
I could not find them when sorting for Australia...

**Comment by lorenz-g** [comment]
I had the project in the list but missed that Tesla would supply the batteries. 
Thanks for pointing it out. 

You can find it here now: https://lorenz-g.github.io/tesla-megapack-tracker/projects/45.html

Do you know of any government data source for large battery projects for Australia by any chance? 
So far I did not have any luck finding one...

**Comment by mlisowsk** [comment]
No idea about Australia gov data source, unfortunately.

**Pull request merged**
